In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import csv

In [3]:
df2015 = pd.read_csv('world-happiness-report/2015.csv')

In [4]:
df2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [5]:
df2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
Country                          158 non-null object
Region                           158 non-null object
Happiness Rank                   158 non-null int64
Happiness Score                  158 non-null float64
Standard Error                   158 non-null float64
Economy (GDP per Capita)         158 non-null float64
Family                           158 non-null float64
Health (Life Expectancy)         158 non-null float64
Freedom                          158 non-null float64
Trust (Government Corruption)    158 non-null float64
Generosity                       158 non-null float64
Dystopia Residual                158 non-null float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [6]:
df2015.drop(['Standard Error'], axis=1, inplace=True) # drop multiple columns

In [7]:
df2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 11 columns):
Country                          158 non-null object
Region                           158 non-null object
Happiness Rank                   158 non-null int64
Happiness Score                  158 non-null float64
Economy (GDP per Capita)         158 non-null float64
Family                           158 non-null float64
Health (Life Expectancy)         158 non-null float64
Freedom                          158 non-null float64
Trust (Government Corruption)    158 non-null float64
Generosity                       158 non-null float64
Dystopia Residual                158 non-null float64
dtypes: float64(8), int64(1), object(2)
memory usage: 13.7+ KB

In [8]:
df2016 = pd.read_csv('world-happiness-report/2016.csv')

In [9]:
df2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [10]:
df2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
Country                          157 non-null object
Region                           157 non-null object
Happiness Rank                   157 non-null int64
Happiness Score                  157 non-null float64
Lower Confidence Interval        157 non-null float64
Upper Confidence Interval        157 non-null float64
Economy (GDP per Capita)         157 non-null float64
Family                           157 non-null float64
Health (Life Expectancy)         157 non-null float64
Freedom                          157 non-null float64
Trust (Government Corruption)    157 non-null float64
Generosity                       157 non-null float64
Dystopia Residual                157 non-null float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.0+ KB

In [11]:
df2016.drop(['Lower Confidence Interval', 'Upper Confidence Interval'], axis=1, inplace=True) # drop multiple columns

In [12]:
df2017 = pd.read_csv('world-happiness-report/2017_2.csv')

In [13]:
df2017.head()

,Country,Region,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Afghanistan,Southern Asia,141,3.794,3.873661,3.714338,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
1,Albania,Central and Eastern Europe,109,4.644,4.752464,4.535536,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
2,Algeria,Middle East and Northern Africa,53,5.872,5.978286,5.765714,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
3,Angola,Sub-Saharan Africa,140,3.795,3.951642,3.638358,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
4,Argentina,Latin America and Caribbean,24,6.599,6.690085,6.507915,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005

In [14]:
df2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 13 columns):
Country                          155 non-null object
Region                           155 non-null object
Happiness.Rank                   155 non-null int64
Happiness.Score                  155 non-null float64
Whisker.high                     155 non-null float64
Whisker.low                      155 non-null float64
Economy..GDP.per.Capita.         155 non-null float64
Family                           155 non-null float64
Health..Life.Expectancy.         155 non-null float64
Freedom                          155 non-null float64
Generosity                       155 non-null float64
Trust..Government.Corruption.    155 non-null float64
Dystopia.Residual                155 non-null float64
dtypes: float64(10), int64(1), object(2)
memory usage: 15.8+ KB

In [15]:
df2017.drop(['Whisker.high', 'Whisker.low'], axis=1, inplace=True) # drop multiple columns

In [16]:
df2015.reindex_axis(sorted(df2015.columns), axis=1).head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption)
0,Switzerland,2.51738,1.39651,1.34951,0.66557,0.29678,1,7.587,0.94143,Western Europe,0.41978
1,Iceland,2.70201,1.30232,1.40223,0.62877,0.43630,2,7.561,0.94784,Western Europe,0.14145
2,Denmark,2.49204,1.32548,1.36058,0.64938,0.34139,3,7.527,0.87464,Western Europe,0.48357
3,Norway,2.46531,1.45900,1.33095,0.66973,0.34699,4,7.522,0.88521,Western Europe,0.36503
4,Canada,2.45176,1.32629,1.32261,0.63297,0.45811,5,7.427,0.90563,North America,0.32957

In [17]:
df2016.reindex_axis(sorted(df2016.columns), axis=1).head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption)
0,Denmark,2.73939,1.44178,1.16374,0.57941,0.36171,1,7.526,0.79504,Western Europe,0.44453
1,Switzerland,2.69463,1.52733,1.14524,0.58557,0.28083,2,7.509,0.86303,Western Europe,0.41203
2,Iceland,2.83137,1.42666,1.18326,0.56624,0.47678,3,7.501,0.86733,Western Europe,0.14975
3,Norway,2.66465,1.57744,1.12690,0.59609,0.37895,4,7.498,0.79579,Western Europe,0.35776
4,Finland,2.82596,1.40598,1.13464,0.57104,0.25492,5,7.413,0.81091,Western Europe,0.41004

In [18]:
# rename one or more columns
df2017.rename(columns={'Happiness.Rank':'Happiness Rank', 'Happiness.Score':'Happiness Score', 'Economy..GDP.per.Capita.':'Economy (GDP per Capita)', 'Health..Life.Expectancy.':'Health (Life Expectancy)', 'Trust..Government.Corruption.':'Trust (Government Corruption)', 'Dystopia.Residual':'Dystopia Residual'}, inplace=True) #saves changes

In [19]:
df2017.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual
0,Afghanistan,Southern Asia,141,3.794,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801
1,Albania,Central and Eastern Europe,109,4.644,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442
2,Algeria,Middle East and Northern Africa,53,5.872,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604
3,Angola,Sub-Saharan Africa,140,3.795,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482
4,Argentina,Latin America and Caribbean,24,6.599,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005

In [20]:
df2017.reindex_axis(sorted(df2017.columns), axis=1).head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption)
0,Afghanistan,2.150801,0.401477,0.581543,0.106180,0.311871,141,3.794,0.180747,Southern Asia,0.061158
1,Albania,1.490442,0.996193,0.803685,0.381499,0.201313,109,4.644,0.731160,Central and Eastern Europe,0.039864
2,Algeria,2.567604,1.091864,1.146217,0.233336,0.069437,53,5.872,0.617585,Middle East and Northern Africa,0.146096
3,Angola,1.614482,0.858428,1.104412,0.000000,0.097926,140,3.795,0.049869,Sub-Saharan Africa,0.069720
4,Argentina,2.614005,1.185295,1.440451,0.494519,0.109457,24,6.599,0.695137,Latin America and Caribbean,0.059740

In [21]:
df2018 = pd.read_csv('world-happiness-report/2018.csv')

In [22]:
df2018.head()

,Country,Region,Happiness Rank,Happiness Score,Dystopia Residual,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
0,Finland,Western Europe,1,7.632,2.59519,1.30510,1.59213,0.87445,0.68063,0.19164,0.39296
1,Norway,Western Europe,2,7.594,2.38324,1.45563,1.58234,0.86076,0.68642,0.28564,0.33969
2,Denmark,Western Europe,3,7.555,2.37018,1.35115,1.59045,0.86793,0.68325,0.28439,0.40792
3,Iceland,Western Europe,4,7.495,2.42599,1.34330,1.64438,0.91380,0.67650,0.35323,0.13802
4,Switzerland,Western Europe,5,7.487,2.31953,1.41973,1.54900,0.92708,0.65978,0.25553,0.35668

In [23]:
df2018.head()

,Country,Region,Happiness Rank,Happiness Score,Dystopia Residual,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
0,Finland,Western Europe,1,7.632,2.59519,1.30510,1.59213,0.87445,0.68063,0.19164,0.39296
1,Norway,Western Europe,2,7.594,2.38324,1.45563,1.58234,0.86076,0.68642,0.28564,0.33969
2,Denmark,Western Europe,3,7.555,2.37018,1.35115,1.59045,0.86793,0.68325,0.28439,0.40792
3,Iceland,Western Europe,4,7.495,2.42599,1.34330,1.64438,0.91380,0.67650,0.35323,0.13802
4,Switzerland,Western Europe,5,7.487,2.31953,1.41973,1.54900,0.92708,0.65978,0.25553,0.35668

In [24]:
df2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
Country                          156 non-null object
Region                           156 non-null object
Happiness Rank                   156 non-null int64
Happiness Score                  156 non-null float64
Dystopia Residual                156 non-null float64
Economy (GDP per Capita)         156 non-null float64
Family                           156 non-null float64
Health (Life Expectancy)         156 non-null float64
Freedom                          156 non-null float64
Generosity                       156 non-null float64
Trust (Government Corruption)    156 non-null float64
dtypes: float64(8), int64(1), object(2)
memory usage: 13.5+ KB

In [25]:
df2018.reindex_axis(sorted(df2018.columns), axis=1).head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption)
0,Finland,2.59519,1.30510,1.59213,0.68063,0.19164,1,7.632,0.87445,Western Europe,0.39296
1,Norway,2.38324,1.45563,1.58234,0.68642,0.28564,2,7.594,0.86076,Western Europe,0.33969
2,Denmark,2.37018,1.35115,1.59045,0.68325,0.28439,3,7.555,0.86793,Western Europe,0.40792
3,Iceland,2.42599,1.34330,1.64438,0.67650,0.35323,4,7.495,0.91380,Western Europe,0.13802
4,Switzerland,2.31953,1.41973,1.54900,0.65978,0.25553,5,7.487,0.92708,Western Europe,0.35668

In [26]:
df2015['Year'] = '2015'

In [27]:
df2016['Year'] = '2016'

In [28]:
df2017['Year'] = '2017'

In [29]:
df2018['Year'] = '2018'

In [30]:
df2015.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015

In [31]:
df2016.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,Year
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939,2016
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463,2016
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137,2016
3,Norway,Western Europe,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465,2016
4,Finland,Western Europe,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596,2016

In [32]:
df2017.head()

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Dystopia Residual,Year
0,Afghanistan,Southern Asia,141,3.794,0.401477,0.581543,0.180747,0.106180,0.311871,0.061158,2.150801,2017
1,Albania,Central and Eastern Europe,109,4.644,0.996193,0.803685,0.731160,0.381499,0.201313,0.039864,1.490442,2017
2,Algeria,Middle East and Northern Africa,53,5.872,1.091864,1.146217,0.617585,0.233336,0.069437,0.146096,2.567604,2017
3,Angola,Sub-Saharan Africa,140,3.795,0.858428,1.104412,0.049869,0.000000,0.097926,0.069720,1.614482,2017
4,Argentina,Latin America and Caribbean,24,6.599,1.185295,1.440451,0.695137,0.494519,0.109457,0.059740,2.614005,2017

In [33]:
df2018.head()

,Country,Region,Happiness Rank,Happiness Score,Dystopia Residual,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption),Year
0,Finland,Western Europe,1,7.632,2.59519,1.30510,1.59213,0.87445,0.68063,0.19164,0.39296,2018
1,Norway,Western Europe,2,7.594,2.38324,1.45563,1.58234,0.86076,0.68642,0.28564,0.33969,2018
2,Denmark,Western Europe,3,7.555,2.37018,1.35115,1.59045,0.86793,0.68325,0.28439,0.40792,2018
3,Iceland,Western Europe,4,7.495,2.42599,1.34330,1.64438,0.91380,0.67650,0.35323,0.13802,2018
4,Switzerland,Western Europe,5,7.487,2.31953,1.41973,1.54900,0.92708,0.65978,0.25553,0.35668,2018

In [34]:
df2015.to_csv('2015-2.csv', index=False)

In [35]:
df2016.to_csv('2016-2.csv', index=False)

In [36]:
df2017.to_csv('2017-2.csv', index=False)

In [37]:
df2018.to_csv('2018-2.csv', index=False)

In [38]:
list_df = [df2015, df2016, df2017, df2018]

df = pd.concat(list_df)

df.head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption),Year
0,Switzerland,2.51738,1.39651,1.34951,0.66557,0.29678,1,7.587,0.94143,Western Europe,0.41978,2015
1,Iceland,2.70201,1.30232,1.40223,0.62877,0.43630,2,7.561,0.94784,Western Europe,0.14145,2015
2,Denmark,2.49204,1.32548,1.36058,0.64938,0.34139,3,7.527,0.87464,Western Europe,0.48357,2015
3,Norway,2.46531,1.45900,1.33095,0.66973,0.34699,4,7.522,0.88521,Western Europe,0.36503,2015
4,Canada,2.45176,1.32629,1.32261,0.63297,0.45811,5,7.427,0.90563,North America,0.32957,2015

In [39]:
np.round(df, decimals = 3).head()

,Country,Dystopia Residual,Economy (GDP per Capita),Family,Freedom,Generosity,Happiness Rank,Happiness Score,Health (Life Expectancy),Region,Trust (Government Corruption),Year
0,Switzerland,2.517,1.397,1.350,0.666,0.297,1,7.587,0.941,Western Europe,0.420,2015
1,Iceland,2.702,1.302,1.402,0.629,0.436,2,7.561,0.948,Western Europe,0.141,2015
2,Denmark,2.492,1.325,1.361,0.649,0.341,3,7.527,0.875,Western Europe,0.484,2015
3,Norway,2.465,1.459,1.331,0.670,0.347,4,7.522,0.885,Western Europe,0.365,2015
4,Canada,2.452,1.326,1.323,0.633,0.458,5,7.427,0.906,North America,0.330,2015

In [40]:
df.to_csv('world-happiness.csv', sep=',')